### PR TITLE
Update example.lua

### PR DESCRIPTION
**Pull request by Oldarorn**

### CODE REVIEW

**Review by Mr-Craig — CHANGES_REQUESTED** [review]
why would you change it? its showing onHovered as the example..?

**Comment by Oldarorn** [comment]
Well, actually I tried the onHovered and it wasn't working before I changed it to onActive (I have the last RageUI update that's why I thought it needed an update)

**Comment by Mr-Craig** [comment]
why don't you fix the issue with the buttons instead?

**Comment by Oldarorn** [comment]
Because it's not broken.. ? It has just an other name.. ?

**Comment by Mr-Craig** [comment]
onHovered and onActive are different.

**Pull request closed without merging**
